# Generated by Django 3.2.5 on 2022-12-07 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e682f4b0-87d7-4de5-b77f-5e8499181756')),
        ),
    ]
