# Generated by Django 3.2.5 on 2022-12-07 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e73084c2-71c3-4019-a6f2-a931821c323a')),
        ),
    ]
