# Generated by Django 3.2.5 on 2022-12-07 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c3a9c97e-1af5-4393-bad1-0b991077e8b0')),
        ),
    ]
