# Generated by Django 3.2.5 on 2022-12-07 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4fb5577e-b73a-4d68-94e7-cc4a6bd0a5a4')),
        ),
    ]
