# Generated by Django 3.2.5 on 2022-12-07 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f9076670-3945-414c-9725-2aed4681f821')),
        ),
    ]
