# Generated by Django 3.2.5 on 2022-12-07 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ce6f0fea-aee6-4b40-8bfa-8186369c57ec')),
        ),
    ]
