# Generated by Django 3.2.5 on 2022-12-07 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20221207_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('98121925-b2f7-4666-9b99-3f6b408a8d3b')),
        ),
    ]
