# Generated by Django 3.2.5 on 2022-12-07 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a41abe1b-1c7e-4d6a-b93e-9242a590de0c')),
        ),
    ]
