# Generated by Django 3.2.5 on 2022-12-07 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_newuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('afda51a2-e58d-46ab-9452-d11621ba1b7e')),
        ),
    ]
